# Generated by Django 4.2.25 on 2025-10-20 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('waggle_app', '0002_remove_profile_role_alter_profile_roles_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner_and_Sitter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('experience', models.IntegerField()),
                ('specialty', models.CharField(blank=True, max_length=500)),
                ('bio', models.CharField(blank=True, max_length=1000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner_and_sitter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
