# Generated by Django 4.2.25 on 2025-10-20 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waggle_app', '0003_owner_and_sitter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='type',
        ),
        migrations.AddField(
            model_name='pet',
            name='species',
            field=models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('bird', 'bird'), ('reptile', 'reptile'), ('fish', 'fish'), ('other', 'Other')], default='dog', max_length=50),
        ),
    ]
