# Generated by Django 4.2.25 on 2025-10-20 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waggle_app', '0004_remove_pet_type_pet_species'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='owner_and_sitter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waggle_app.owner_and_sitter'),
        ),
    ]
