# Generated by Django 4.2.25 on 2025-10-20 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waggle_app', '0005_pet_owner_and_sitter'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner_and_sitter',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waggle_app.owner'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='owner',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='waggle_app.owner'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='owner_and_sitter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waggle_app.owner_and_sitter'),
        ),
    ]
