# Generated by Django 4.2.25 on 2025-10-21 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waggle_app', '0006_owner_and_sitter_owner_alter_pet_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='owner_and_sitter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='waggle_app.owner_and_sitter'),
        ),
    ]
