# Generated by Django 4.2.25 on 2025-10-21 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waggle_app', '0007_alter_pet_owner_and_sitter'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner_and_sitter',
            name='rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sitter',
            name='rate',
            field=models.IntegerField(default=0),
        ),
    ]
