# Generated by Django 4.2.25 on 2025-10-21 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waggle_app', '0008_owner_and_sitter_rate_sitter_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='owner_and_sitter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings_received', to='waggle_app.owner_and_sitter'),
        ),
    ]
