# Generated by Django 4.2.25 on 2025-10-21 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waggle_app', '0009_booking_owner_and_sitter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='sitter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings_received', to='waggle_app.sitter'),
        ),
    ]
